export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGPRIES_START: 'catergory/FETCH_CATEGPRIES_START',
    FETCH_CATEGPRIES_SUCESS: 'catergory/FETCH_CATEGPRIES_SUCESS',
    FETCH_CATEGPRIES_FAILED: 'catergory/FETCH_CATEGPRIES_FAILED',
}