export const CART_ACTION_TYPES = {
    SET_IS_CARTOPEN : "cart/SETISCARTOPEN",
    SET_CART_ITEMS : "cart/ADDITEMSTOCART",
    SET_CART_COUNT : "cart/SET_CART-COUNT",
    SET_CART_TOTAL : "cart/SET_CART_TOTAL "
}